### ISSUE TITLE
ændre plugin så den benytter ny rettigheds service

### ISSUE THREAD

**Issue by DocDemar** [SDFIdk/Qgis-dataforsyningen#19]
ændre så den benytter json istedet for XML

**Comment by Nobralyra** [comment]
Link til fil, hvor rettighedsservicen bliver kaldt (variabel: DF_SERVICES_URL), som skal rettes til den nye rettighedsservice:
https://github.com/SDFIdk/Qgis-dataforsyningen/blob/master/Dataforsyningen/df_config.py
