### ISSUE TITLE
Alle WFS kald opfører sig forkert

### ISSUE THREAD

**Issue by Nobralyra** [SDFIdk/Qgis-dataforsyningen#25]
Ligner det er koden der gør mærkeligt.
Qgis laver følgende kald: `?SERVICE=WFS&REQUEST=GetCapabilities&ACCEPTVERSIONS=2.0.0,1.1.0,1.0.0`.

Hvor fx WFS for GeoDanmark60_NOHIST_GML3_DAF burde være: `https://api.dataforsyningen.dk/GeoDanmark60_NOHIST_GML3_DAF?token={}&SERVICE=WFS&REQUEST=GetCapabilities&ACCEPTVERSIONS=2.0.0,1.1.0,1.0.0`.

**Comment by JesperKock** [comment]
Ved at fjerne parameterne foran `url=` ser GetCapabilities kaldet for WFS korrekt ud i QGIS men WFS laget bliver ikke hentet ned i QGIS.

**Comment by JesperKock** [comment]
Parameterne i datasource var ved en fejl antaget som en del af api kaldet og derfor tilføjet til url kaldet med url encoded '&'.
Specifikt var parameteren 'typename' et krav for WFS kald, under datasource tagget i QLR filen.
