### ISSUE TITLE
No contact to Dataforsyningen: Check internet connection and Dataforsyningen settings

### ISSUE THREAD

**Issue by lauratechrem** [SDFIdk/Qgis-dataforsyningen#35]
Hej

Jeg er en ny bruger a QGIS. Når jeg prøver at installere Dataforsynningen plugin in set står "Check internet connection and Dataforsyningen settings".
Jeg har checket min profil i dataforsyning od det ser ud som det skal .
Jeg har også dpwnloaded plugin, hvis det hjelper.

Tak

**Comment by JesperKock** [comment]
Hej, hvis plugin'et virker på trods af fejlbeskedet så er det nok samme fejl som her #29

**Comment by lauratechrem** [comment]
Nej det virker ikke. Jeg prøvede at upload a qrl file som jeg så i anden post.

**Comment by JesperKock** [comment]
Så vidt jeg kan se så virker vores tjenster fint ligenu.

Kan du kontakte vores support afdeling? de vil med glæde hjælpe dig i gang med QGIS: [Dataforsyningen - Få hjælp](https://dataforsyningen.dk/help)

**Comment by lauratechrem** [comment]
TAK! Jeg skal nok kontakte dem.
