### ISSUE TITLE
Ingen kontakt til Dataforsyningen: Tjek internetforbindelse og Dataforsyningens indstillinger

### ISSUE THREAD

**Issue by KlausJakobsen73** [SDFIdk/Qgis-dataforsyningen#37]
Den sidste uges tid har jeg ikke kunnet få QGIS's adgang til dataforsorsyningen til at virke
Jeg har prøvet at 
 - oprette 1 ny token
 - afinstallere Dataforsyningens plugin og geninstallere
 - afinstallere QGIS og installere igen
 - har prøvet på en hel frisk PC
 - Har også prøvet med nyt Token på den nye PC

Intet har hjulpet
Jeg kører:

QGIS-version    3.40.0-Bratislava

Jeg tror fejlen startede med at jeg fik at vide at min QGIS var for gammel og at jeg derfor måtte opgradere.

Jeg har 2 venner som har samme oplevelse, med at det er holdt op med at virke og at det er ca. en uges tid siden.

**Comment by JesperKock** [comment]
Datafordeleren har været meget ustabil på det seneste og de påvirker desværre lagene i vores plugin. Pga. udfaldene har vi pt. helt lukket for WMS lagene, f.eks baggrundskortene. Heldigvis har vi for nylig tilføjet vector tiles versioner af baggrundskortene. Disse skulle virke pt.

Beskeden `Ingen kontakt til Dataforsyningen: Tjek internetforbindelse og Dataforsyningens indstillinger` burde dog ikke dukke op ligenu.

**Comment by LDalby** [comment]
Hmm, jeg og et par kolleger får p.t. denne:
```
2024-12-02T09:58:43     WARNING    Download of capabilities failed:
             Error transferring https://api.dataforsyningen.dk/topo_skaermkort_DAF?token=edb24d5830db513039e0780668f3f5b4&SERVICE=WMS&REQUEST=GetCapabilities - server replied: 
2024-12-02T09:59:25     WARNING    Download of capabilities failed:
             Error transferring https://api.dataforsyningen.dk/topo_skaermkort_DAF?token=edb24d5830db513039e0780668f3f5b4&SERVICE=WMS&REQUEST=GetCapabilities - server replied: 
2024-12-02T09:59:36     WARNING    Download of capabilities failed:
             Not Found
2024-12-02T09:59:44     WARNING    Download of capabilities failed:
             Not Found
```
Det er vel relateret til dette issue også @JesperKock ?

**Comment by JesperKock** [comment]
@LDalby Korrekt. `topo_skaermkort_DAF` er nede i øjeblikket. Fanen `vector tiles` har et baggrundskort der gerne skulle virke.

**Comment by LDalby** [comment]
OK, tak for svar!

Regner I med at diverse WMS-lag kommer i luften igen, eller hvordan ser I på det?

**Comment by JesperKock** [comment]
Vi har åbnet op for lagene igen.

Der er dog en stærk begrænsning på antallet af kald der kan fortages til de tjenster der slutter på `_daf`. Jeg ved desværre ikke hvornår Datafordeler tjenesterne er tilbage til normal.

**Comment by JesperKock** [comment]
Driftinformation kan ses her: https://dataforsyningen.dk/news/5004

Lukker issuet.
